#!/usr/bin/env bash
# input: pinned family/weight request to the public Google Fonts CSS endpoint
# output: verified, content-addressed, compact self-hosted WOFF2 bundle in public/fonts
# pos: local-only font regeneration; never run in production or a publish workflow
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FINAL_DIR="$ROOT_DIR/public/fonts"
BUILD_ROOT="$(mktemp -d "$ROOT_DIR/public/.fonts-build.XXXXXX")"
OUT_DIR="$BUILD_ROOT/fonts"
TMP_CSS="$BUILD_ROOT/google.css"
BACKUP_DIR="$ROOT_DIR/public/.fonts-backup.$$"
CSS_URL="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Noto+Sans+SC:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126 Safari/537.36"

cleanup() {
  rm -rf "$BUILD_ROOT"
  if [ -d "$BACKUP_DIR" ] && [ ! -d "$FINAL_DIR" ]; then mv "$BACKUP_DIR" "$FINAL_DIR"; fi
}
trap cleanup EXIT
mkdir -p "$OUT_DIR"
curl -L --fail --show-error --max-time 60 -H "User-Agent: $UA" "$CSS_URL" -o "$TMP_CSS"

python3 - "$TMP_CSS" "$OUT_DIR" <<'PY'
import hashlib
import pathlib
import re
import sys
import urllib.request

css_path = pathlib.Path(sys.argv[1])
out_dir = pathlib.Path(sys.argv[2])
css = css_path.read_text(encoding="utf-8")
urls = sorted(set(re.findall(r"https://fonts\.gstatic\.com/[^)]+?\.woff2", css)))
if not urls:
    raise RuntimeError("Google Fonts CSS contained no WOFF2 URLs")

for index, url in enumerate(urls, start=1):
    with urllib.request.urlopen(url, timeout=60) as response:
        data = response.read()
    if len(data) < 4 or data[:4] != b"wOF2":
        raise RuntimeError(f"Invalid WOFF2 response from {url}")
    digest = hashlib.sha256(data).hexdigest()[:16]
    original = pathlib.Path(url.split("?")[0]).name
    filename = f"{index:03d}-{digest}-{original}"
    (out_dir / filename).write_bytes(data)
    css = css.replace(url, filename)

banner = """/*
 * Self-hosted WithMedia font bundle.
 * Generated by scripts/fetch-fonts.sh.
 * Families: Space Grotesk, Noto Sans SC, JetBrains Mono.
 * font-display: swap; URLs are relative to this same-origin stylesheet.
 */
"""
(out_dir / "fonts.css").write_text(banner + css, encoding="utf-8")
print(f"downloaded {len(urls)} verified font files")
PY

python3 "$ROOT_DIR/scripts/compact_font_css.py" "$OUT_DIR/fonts.css"
font_count="$(find "$OUT_DIR" -type f -name '*.woff2' | wc -l | tr -d ' ')"
[ "$font_count" -gt 0 ] || { echo "font bundle is empty" >&2; exit 1; }
if [ -d "$FINAL_DIR" ]; then mv "$FINAL_DIR" "$BACKUP_DIR"; fi
mv "$OUT_DIR" "$FINAL_DIR"
rm -rf "$BACKUP_DIR"
echo "installed $font_count verified fonts in $FINAL_DIR"
