#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT_DIR/public/fonts"
CSS_URL="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Noto+Sans+SC:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

TMP_CSS="$(mktemp)"
trap 'rm -f "$TMP_CSS"' EXIT # clean up on any exit path, not just the happy path
curl -L --fail --show-error --max-time 60 -H "User-Agent: $UA" "$CSS_URL" -o "$TMP_CSS"

python3 - "$TMP_CSS" "$OUT_DIR" <<'PY'
import hashlib
import pathlib
import re
import sys
import urllib.request

css_path = pathlib.Path(sys.argv[1])
out_dir = pathlib.Path(sys.argv[2])
css = css_path.read_text()
urls = sorted(set(re.findall(r"https://fonts\.gstatic\.com/[^)]+?\.woff2", css)))

for index, url in enumerate(urls, start=1):
    digest = hashlib.sha1(url.encode("utf-8")).hexdigest()[:10]
    original = pathlib.Path(url.split("?")[0]).name
    filename = f"{index:03d}-{digest}-{original}"
    target = out_dir / filename
    with urllib.request.urlopen(url, timeout=60) as response:
        target.write_bytes(response.read())
    css = css.replace(url, f"/fonts/{filename}")

banner = """/*
 * Self-hosted WithMedia font bundle.
 * Generated by scripts/fetch-fonts.sh.
 * Families: Space Grotesk, Noto Sans SC, JetBrains Mono.
 * font-display: swap; all URLs are same-origin under /fonts/.
 */
"""
(out_dir / "fonts.css").write_text(banner + css)
print(f"downloaded {len(urls)} font files to {out_dir}")
PY
